### ISSUE TITLE
Metric Documentation

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#112]
@EssentiallyNoah 

In documentation, should have formal definition of the metric, as well as how we particularly implemented it and what limitations there might be about those implementations.

**Comment by EssentiallyNoah** [comment]
Templates for metric definitions and implementation details have been added to the documentation branch. Looking for help to fill this information in across all the metrics in NeuroBench.

**Comment by EssentiallyNoah** [comment]
Completed #151
