### ISSUE TITLE
Metric output multiple values

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#113]
@korneelf1 
The synaptic ops metric would benefit from discerning between MACs (because of float activations) vs ACs (because of binary activation). This could be implemented in the synops metric by checking whether the layer output is binary.

We could make the synops an AccumulatedMetric which saves the state of both MACs and ACs and returns a dict as output, so metric out would be `'synaptic_operations': {'MACs': X, 'ACs': Y}`.

For the baselines, this would only be relevant for the Hybrid ANN/SNN for the obj detection, as all other models are doing either all MACs or all ACs.

**Comment by korneelf1** [comment]
Done in effective_macs branch

Remarks:
- inputs that are all ones will be counted as ACs only
- Biases in ANN will be counted as MACs
