### ISSUE TITLE
Automatic downloading of datasets

### ISSUE THREAD

**Issue by EssentiallyNoah** [NeuroBench/neurobench#118]
MSWC, Primate Reaching, and Metavision should be automatically downloaded if wanted by the user. This would likely take the form of a `download` flag in the individual Dataloaders

**Comment by tao-sun** [comment]
I am working on this issue.

**Comment by tao-sun** [comment]
@EssentiallyNoah can we copy and use the pytorch vision code?

**Comment by jasonlyik** [comment]
TODO: check license info / adding licenses for these datasets

**Comment by jasonlyik** [comment]
Finishing in #161
