### ISSUE TITLE
torch, torchaudio, and metavision_ml are mock imports due to docugen issues

### ISSUE THREAD

**Issue by EssentiallyNoah** [NeuroBench/neurobench#123]
Can this be fixed? Does it have any impact on the documentation quality?

**Comment by jasonlyik** [comment]
Try making torch lightning mock import to fix documentation here: https://neurobench.readthedocs.io/en/latest/neurobench.datasets.html#wireless-sensor-data-mining

**Comment by jasonlyik** [comment]
<img width="714" alt="image" src="https://github.com/NeuroBench/neurobench/assets/42597690/f0ff5837-04d2-4f4d-921c-435cc9f15753">
@ben9809 After adding pytorch_lightning as mock import, the documentation looks like above. It is sparse, but probably better than the current docs which are bloated with lightning docs: https://neurobench.readthedocs.io/en/latest/neurobench.datasets.html#wireless-sensor-data-mining

What do you think about the dataset documentation?

**Comment by ben9809** [comment]
@jasonlyik it looks way better. I could add more detailed documentation for the `class WISDM` and the two methods `convert_to_tensor` and  `create_directory`

**Comment by jasonlyik** [comment]
Sounds good, please feel free to make the commits directly to the documentation branch
