### ISSUE TITLE
Add tutorial for MSWC task

### ISSUE THREAD

**Issue by EssentiallyNoah** [NeuroBench/neurobench#154]
A tutorial is needed showing users how to run the MSWC task.

**Comment by Maxtimer97** [comment]
Tutorial means a jupyter notebook to run the example step by step?

I can also help with that if needed @jasonlyik

**Comment by V0XNIHILI** [comment]
Currently in progress in #158

**Comment by V0XNIHILI** [comment]
This one can be closed I think, per #150
