### ISSUE TITLE
Example bugs

### ISSUE THREAD

**Issue by bucklesm** [NeuroBench/neurobench#165]
Just starting with the repo and testing the examples. Following issues:
- primate_reaching
    - There is no SNN model in this example, though it is reported in the paper.
- examples/mswc_fscil.py `from neurobench.datasets import MSWC_FSCIL` doesn’t work/exist in datasets. 
- examples/obj_detection.py `from neurobench.datasets import Prophesee1MP` doesn’t exist in the datasets folder.

**Comment by jasonlyik** [comment]
Thanks for checking out the repo @bucklesm! 
We're finalizing cleanup now in the `dev` branch before moving everything over to `main`, there are a ton of updates that we're going to push for a polished v1.0.

**Comment by bucklesm** [comment]
Thanks @jasonlyik! I have been playing with the NHP task, in both the `main` and `dev` branches. I've found it tricky to parse what the input data is as well as some of the processing that seems to happen within the ANN (and how you choose the dividing line for "pre-processing"). I'm looking forward to the v1.0. If there's a document describing the data flow (especially for the NHP benchmark) a little in the meantime, I'd love to take a look.

**Comment by jasonlyik** [comment]
@bucklesm For the regression tasks NHP and MackeyGlass, we use a slightly different data format where each timestep is considered a different sample, and the prediction is the next timestep data. So the data tensor ends up as `[B, T, F]`, `B = number of samples (timesteps) to predict`, `T = 1 timestep per sample`, `F = 96 or 192 spike features`. We can add more detail to the tutorials with the full version up as well!
