### ISSUE TITLE
Poetry Lock seems to have some git merging artifacts which makes it unreadable.

### ISSUE THREAD

**Issue by Maxtimer97** [NeuroBench/neurobench#172]
https://github.com/NeuroBench/neurobench/blob/375e67cbfa7a7ccae919d2cd8e86b85645a555c9/poetry.lock#L2729C1-L2749C12

**Comment by Maxtimer97** [comment]
Additionally, poetry.toml references README.md instead of the current README.rst, which create the following issue:
`The current project could not be installed: [Errno 2] No such file or directory: '...\\neurobench\\README.md'`
(https://github.com/NeuroBench/neurobench/blob/375e67cbfa7a7ccae919d2cd8e86b85645a555c9/pyproject.toml#L6C1-L6C21)

**Comment by jasonlyik** [comment]
Looks like the README issue is fixed but there is still the merge artifacts which mess up the poetry.lock, not cleared yet

**Comment by jasonlyik** [comment]
Fixed e275f5c299cdb2ffd9f96c8d97565be816970615
