### ISSUE TITLE
Poetry MSWC SNN bug

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#177]
Due to new version of torchaudio (2.1.2), which uses ffmpeg backend for decompressing opus vs the older 2.0.2 which uses sox_io, the MSWC SNN is broken. 

Use wav files from HF instead of opus files:
- Not possible with the word selection because not all of the dataset is available in wav.

Adding eps of 1e-6 to melspecgram before taking log in S2S, poetry run:
- GSC SNN without eps: 
  - 'classification_accuracy': 0.848432529519656, 'activation_sparsity': 0.967613262583072, 'Effective_ACs': 3395286.9895502045
- GSC SNN with eps: 
  - 'classification_accuracy': 0.8564288947648321, 'activation_sparsity': 0.9676503746614553, 'Effective_ACs': 3290823.3114039074
- MSWC SNN (before proto) without eps, base words: 
  - 'classification_accuracy': 0.011299999999999998, 'activation_sparsity': 0.9220476215115827, 'Effective_ACs': 69445443.028
- MSWC SNN (before proto) with eps, base words:
  - 'classification_accuracy': 0.9214999999999998, 'activation_sparsity': 0.9170702291763837, 'Effective_ACs': 71508560.5244

**Comment by Maxtimer97** [comment]
The epsilon trick looks good but it still requires people to install the ffpmeg backend and have this weird conversion of opus files. Plus the epsilon trick is a bit weird to explain for the paper.

Could we rather try to manually convert the opus files to a standard format like wav and see what we get with that? 
This way the dataset will be lighter + a better experience for future users.

**Comment by jasonlyik** [comment]
TODO: add log_offset to S2S as an option, as default option

**Comment by jasonlyik** [comment]
d1f05afd8dbbc039a1251205ea91741947db7556
