### ISSUE TITLE
Add docs url as site url on the of the main Github page

### ISSUE THREAD

**Issue by V0XNIHILI** [NeuroBench/neurobench#188]
Compare:
<img width="269" alt="image" src="https://github.com/NeuroBench/neurobench/assets/24796206/fed72676-b73c-4154-b677-7fa36a6bcbb6">

<img width="271" alt="image" src="https://github.com/NeuroBench/neurobench/assets/24796206/01eb3555-e5a7-4153-99d5-975450e281ab">

**Comment by jasonlyik** [comment]
Looks good, added
