### ISSUE TITLE
Mismatch between documentation and code

### ISSUE THREAD

**Issue by V0XNIHILI** [NeuroBench/neurobench#189]
See output shape of audio sample:
<img width="668" alt="image" src="https://github.com/NeuroBench/neurobench/assets/24796206/28c0de7e-e176-45db-b417-1f56010d6cbb">
And in docs:
<img width="473" alt="image" src="https://github.com/NeuroBench/neurobench/assets/24796206/afa1847b-a894-4827-afd5-f48ff7bb0ca8">
However, for all PyTorch audio datasets the shape is (1, timesteps) instead of (timesteps, 1). Should we remove the transpose to the audio here?
https://github.com/NeuroBench/neurobench/blob/c01253236d6e84eb5af5cd0c0fdf1bdd84b2bed4/neurobench/datasets/MSWC_dataset.py#L244

**Comment by jasonlyik** [comment]
Code is correct, documentation is wrong. We want to match the NeuroBench convention of (timesteps, features).

50d855cbd5b361699f48038443a7a5397f5ca855
