### ISSUE TITLE
Results Output Format

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#32]
Results output formatting to terminal and to file.

Simple idea would be results in dict, pretty print to terminal and output to JSON file

Other things
- Should count benchmark run (for iterative learning tasks)

**Comment by korneelf1** [comment]
Dump the entire output

**Comment by jasonlyik** [comment]
For this we might as well just use pprint to pretty print the dict.

`import pprint`
`results = benchmark.run()`
`pprint.pp(results)`
