### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by YounesBouhadjar** [NeuroBench/neurobench#40]
These are initial documentation guidelines:

- Add a header to your code/data analysis scripts
  - Describe what the scripts are supposed to do
  - Mention the authors
  - Mention the LICENSE
  - Example:

```
# Copyright
# LICENSE
#
#

"""
Title of the file
------------------------------------------------------------
Description of the code


References
~~~~~~~~~~

.. [1] xxxx

Authors
~~~~~~~
yyyy
"""
 ```

- Add docstring to the different functions
  - Describe what each function does
  - Describe the function’s parameters and the returned values
  - Mention warnings, exceptions, errors, examples and todos
  - We aim to use **Google style Python Docstrings**, see here for an example: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by EssentiallyNoah** [comment]
Closing. Will track more granularly in #92.
