### ISSUE TITLE
Augment data to work with kwargs

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#65]
1MP task COCO metric implementation requires that additional video metadata is used (https://arxiv.org/pdf/2009.13436.pdf, Appendix B). 

Need to augment the data interface to have kwargs dict at data[2]
dataset = (input, labels, kwargs**)

This needs to be done before / along with COCO metric implementation #17 

Also need to update the 1MP dataloader to package samples this way

**Comment by EssentiallyNoah** [comment]
#72
