### ISSUE TITLE
Downgrade to Python3.9

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#67]
Currently pyproject.toml dependency lists python3.10

Metavision is only compatible with 3.8, 3.9 in ubuntu20, and 3.9, 3.10 in ubuntu22. Downgrade to 3.9 would cover these cases.

Downgrade will break `glob` with `root_dir` parameter, which is only added in python3.10

**Comment by EssentiallyNoah** [comment]
Closing with #79
