### ISSUE TITLE
Staging area for new tasks

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#68]
Organization - add staging area / documentation for new tasks which are built by community, but not necessarily part of a NeuroBench version (which will be the officially reported benchmarks). Staged tasks can make their way into a version through some process, maybe some vote from the community or some committee review.

New tasks should be implemented just like the existing tasks.

**Comment by korneelf1** [comment]
Implement as last task, will change file structure

**Comment by jasonlyik** [comment]
Going forward, there won't be any difference in the harness between "official" and "unofficial" tasks. If you want to submit a new benchmark, i.e. dataset / metrics, etc., just submit a PR and it will be incorporated.
