### ISSUE TITLE
Ignore neurobench/examples/model_data in pypi

### ISSUE THREAD

**Issue by jasonlyik** [NeuroBench/neurobench#73]
In deployment to pypi the saved models for the examples shouldn't be included in the package, but they should be on the repo to reproduce results and use. There is probably something in poetry to do this.

**Comment by EssentiallyNoah** [comment]
It looks like the entire example folder only takes up 2.2M of space. We might consider leaving the model weights for now as it could help people recreate our results down the road. Certainly if it gets too bloated, we can remove them.

**Comment by jasonlyik** [comment]
The baseline obj detection models are 90MB (ANN) and 10MB (Hybrid ANN-SNN)

**Comment by EssentiallyNoah** [comment]
neurobench/examples, docs, and tests directories are now being excluded from the poetry build process
