### ISSUE TITLE
Finalize Documentation

### ISSUE THREAD

**Issue by EssentiallyNoah** [NeuroBench/neurobench#92]
There's a lot of documentation polishing to do. A rough draft can be found in the documentation branch. A quick list of things that need to be done can be found under docs/readme.rst. Further edits to the documentation can be made here. This branch will be pulled into main on every major release.

**Comment by jasonlyik** [comment]
@AuroraMicheli is interested in helping out with this

**Comment by jasonlyik** [comment]
Check out branches:
- documentation
- prototype_task_staging

**Comment by korneelf1** [comment]
@AuroraMicheli, I see you have forked from the main branch. Be sure to fork from the dev branch as this is the branch where developments that will be pushed to the main (official release branch) are implemented.

**Comment by AuroraMicheli** [comment]
The docs/readme.rst file can be updated: at least the 1., 2., 3., 7., 10. points seem to be done at the moment.

**Comment by thekatiedee** [comment]
hey, it kinda looks like it's been covered already, but did you need any more documentation help? looking for ways to contribute. thanks!

**Comment by EssentiallyNoah** [comment]
Closing this to break out documentation changes into more granular tasks
